import { RECIPE_SCHEMA } from "../store-candidate.ts";
import type { Recipe } from "../recipe.ts";

const requirementsBoard = {
  endRelation: "parallel",
  lengthDatum: "long-long-outer-edge",
  endIdentity: "miter-face-long-point",
} as const;

const requirementsSquare = {
  endRelation: "parallel",
  lengthDatum: "square-end-to-square-end",
  endIdentity: "square-end",
} as const;

const woods = [
  { key: "construction", species: "spf", grade: "construction" },
  { key: "treated", species: "syp-treated", grade: "above-ground" },
  { key: "ground-contact", species: "syp-treated", grade: "ground-contact" },
  { key: "cedar-tone", species: "syp-treated", grade: "ground-contact-cedartone" },
  { key: "cedar", species: "cedar", grade: "S4S" },
];

const woodChoices = [
  { value: "construction", label: "Construction SPF" },
  { value: "treated", label: "Treated, above ground" },
  { value: "ground-contact", label: "Ground-contact treated" },
  { value: "cedar-tone", label: "Cedar-tone treated" },
  { value: "cedar", label: "Cedar S4S" },
];

const finishes = [
  { value: "BYO", label: "Bring your own hardware" },
  { value: "coated", label: "Coated" },
  { value: "hot-dip-galvanized", label: "Hot-dip galvanized" },
  { value: "stainless", label: "Stainless" },
  { value: "silicon-bronze", label: "Silicon bronze" },
];

const plans = [
  {
    id: "a-frame",
    title: "Classic A-frame",
    source: "Published picnic-table plan: 6 ft, seats 8, 2×6 + 2×4 + 2×2. Legs and cross supports are 25° off square, ends parallel, long point to short point.",
    groups: [
      { id: "SLATS", nominalT: 2, nominalW: 6, angleDeg: 0, scales: true, parts: [{ id: "TOP", count: 6, lengthIn: 0 }, { id: "SEAT", count: 6, lengthIn: 0 }] },
      { id: "LEGS", nominalT: 2, nominalW: 6, angleDeg: 25, parts: [{ id: "LEG", count: 4, lengthIn: 31.375 }] },
      { id: "BRACES", nominalT: 2, nominalW: 4, angleDeg: 25, parts: [{ id: "BRACE", count: 2, lengthIn: 32.875 }] },
      { id: "SUPPORTS", nominalT: 2, nominalW: 4, angleDeg: 0, parts: [{ id: "SUPPORT", count: 2, lengthIn: 61 }] },
      { id: "CLEATS", nominalT: 2, nominalW: 2, angleDeg: 0, parts: [{ id: "CLEAT-END", count: 2, lengthIn: 34.25 }, { id: "CLEAT-MID", count: 1, lengthIn: 29.25 }] },
    ],
    hardware: [
      { id: "S25", need: 100, requirement: { kind: "wood-screw", gauge: "#10", lengthIn: 2.5 } },
    ],
  },
  {
    id: "table-benches",
    title: "Table and two benches",
    source: "Published picnic-table plan: 6 ft, all 2×4, square cuts. Screw and bolt counts are this project's reading of that plan; the plan publishes no gauge.",
    groups: [
      { id: "SLATS", nominalT: 2, nominalW: 4, angleDeg: 0, scales: true, parts: [{ id: "TABLE-SLAT", count: 7, lengthIn: 0 }, { id: "BENCH-SLAT", count: 6, lengthIn: 0 }] },
      {
        id: "FRAMES",
        nominalT: 2,
        nominalW: 4,
        angleDeg: 0,
        parts: [
          { id: "TABLE-LEG", count: 4, lengthIn: 26 },
          { id: "TABLE-SUPPORT", count: 4, lengthIn: 27.5 },
          { id: "BENCH-LEG", count: 8, lengthIn: 16.5 },
          { id: "BENCH-SUPPORT", count: 8, lengthIn: 11.5 },
        ],
      },
    ],
    hardware: [
      { id: "S45", need: 26, requirement: { kind: "wood-screw", gauge: "#10", lengthIn: 4.5 } },
      { id: "S25", need: 48, requirement: { kind: "wood-screw", gauge: "#10", lengthIn: 2.5 } },
      { id: "CB", need: 8, requirement: { kind: "carriage-bolt", diameterIn: 0.375, lengthIn: 5 } },
    ],
  },
];

export const LIBRARY: Recipe[] = [
  {
    schema: RECIPE_SCHEMA,
    recipeId: "start-own",
    version: "1",
    title: "Start your own",
    summary: "Two braces on one board, with a face miter and a centered spot.",
    narrative:
      "You name the species. The workpiece length is the board you are defining, not a count of cuts. Each brace is its own part. A spot, when you ask for one, sits at the middle of that part. The Store chooses the stock and the price.",
    engine: "supported",
    requestType: "USER_DEFINED_BOARD_V1",
    classId: "app.user-defined-board.v1",
    configurationId: "SYO-USER1-XBRACE",
    requirements: requirementsBoard,
    inputs: [
      { id: "title", label: "Job title", kind: "text", required: true },
      { id: "species", label: "Species", kind: "text", required: true, help: "No default. The Store will not pick a species for you." },
      { id: "workpieceLengthIn", label: "Defined workpiece length (in)", kind: "number", required: true },
      { id: "partCount", label: "Number of braces", kind: "integer", required: true },
      { id: "partLengthIn", label: "Each brace length (in)", kind: "number", required: true },
      { id: "sawAngleDeg", label: "Face miter (degrees)", kind: "number", required: true },
      { id: "spots", label: "Centered spot on each brace", kind: "boolean", required: true },
    ],
    defaults: {
      title: "Start Your Own — User 1 X brace",
      species: "",
      workpieceLengthIn: 60,
      partCount: 2,
      partLengthIn: 16,
      sawAngleDeg: 30,
      spots: true,
    },
    rule: {
      op: "board-workpiece",
      title: { input: "title" },
      species: { input: "species" },
      nominalT: { literal: 2 },
      nominalW: { literal: 4 },
      workpieceLengthIn: { input: "workpieceLengthIn" },
      partCount: { input: "partCount" },
      partLengthIn: { input: "partLengthIn" },
      sawAngleDeg: { input: "sawAngleDeg" },
      spots: { input: "spots" },
      configurationVersion: { literal: "0.1" },
    },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "project-1",
    version: "1",
    title: "Project 1 specimen",
    summary: "The published 18 in treated brace. Same board rule as Start your own. Not a special path.",
    narrative:
      "Two 18 in parts, treated southern yellow pine, 2×4, face miter 26.387799961243°, one centered spot on each part, 60 in defined workpiece. The published review recorded Q $11.09 and a virtual time that does not equal the Store time. This job does not overwrite either number.",
    engine: "supported",
    requestType: "USER_DEFINED_BOARD_V1",
    classId: "app.user-defined-board.v1",
    configurationId: "SYO-USER1-XBRACE",
    requirements: requirementsBoard,
    inputs: [
      { id: "title", label: "Job title", kind: "text", required: true },
      { id: "species", label: "Species", kind: "text", required: true },
      { id: "workpieceLengthIn", label: "Defined workpiece length (in)", kind: "number", required: true },
      { id: "partCount", label: "Number of parts", kind: "integer", required: true },
      { id: "partLengthIn", label: "Each part length (in)", kind: "number", required: true },
      { id: "sawAngleDeg", label: "Face miter (degrees)", kind: "number", required: true },
      { id: "spots", label: "Centered spot on each part", kind: "boolean", required: true },
    ],
    defaults: {
      title: "Project 1 reference specimen",
      species: "syp-treated",
      workpieceLengthIn: 60,
      partCount: 2,
      partLengthIn: 18,
      sawAngleDeg: 26.387799961243,
      spots: true,
    },
    rule: {
      op: "board-workpiece",
      title: { input: "title" },
      species: { input: "species" },
      nominalT: { literal: 2 },
      nominalW: { literal: 4 },
      workpieceLengthIn: { input: "workpieceLengthIn" },
      partCount: { input: "partCount" },
      partLengthIn: { input: "partLengthIn" },
      sawAngleDeg: { input: "sawAngleDeg" },
      spots: { input: "spots" },
      configurationVersion: { literal: "0.2" },
    },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "alcove",
    version: "1",
    title: "Alcove",
    summary: "Uprights and shelf strips for an opening. The shelf layout is your choice.",
    narrative:
      "Four uprights and shelves across a depth. Whole boards are used until the depth has a remainder. That remainder is one strip ripped to the finished width, not a different project type. The pins-and-screws kit is a requirement id. This System does not name the Store's SKU.",
    engine: "supported",
    requestType: "CUT_PACKAGE_V1",
    configurationId: "ALCOVE-INSERT",
    requirements: requirementsSquare,
    inputs: [
      { id: "species", label: "Species", kind: "text", required: true },
      { id: "grade", label: "Grade", kind: "text", required: true, help: "Required. Leaving it blank does not let the Store choose." },
      { id: "nominalW", label: "Nominal width", kind: "integer", required: true },
      { id: "heightIn", label: "Upright height (in)", kind: "number", required: true },
      { id: "depthIn", label: "Shelf depth (in)", kind: "number", required: true },
      { id: "spanIn", label: "Shelf span (in)", kind: "number", required: true },
      { id: "shelfCount", label: "Number of shelves", kind: "integer", required: true },
    ],
    defaults: { species: "pine", grade: "select", nominalW: 6, heightIn: 65, depthIn: 14, spanIn: 44, shelfCount: 5 },
    rule: {
      op: "depth-strips",
      species: { input: "species" },
      grade: { input: "grade" },
      nominalW: { input: "nominalW" },
      heightIn: { input: "heightIn" },
      depthIn: { input: "depthIn" },
      spanIn: { input: "spanIn" },
      shelfCount: { input: "shelfCount" },
      uprightCount: { literal: 4 },
    },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "window-seat",
    version: "1",
    title: "Window seat",
    summary: "Towers, seat and cubbies from the sketch rules. This one is an engine extension.",
    narrative:
      "Width is three sections. Depth becomes the fewest 1× boards that cover it. The top tower shelf lines up with the window head. Shelves below split the space evenly. Side spots are off until you ask, and only at a declared inset. An extra hand-placed spot from the old page is not in this candidate.",
    engine: "extension",
    extensionId: "window-seat-layout/1",
    requestType: "CUT_PACKAGE_V1",
    configurationId: "WINDOW-SEAT",
    requirements: requirementsSquare,
    inputs: [
      { id: "species", label: "Species", kind: "choice", required: true, choices: [
        { value: "pine", label: "Select pine" },
        { value: "poplar", label: "Select poplar" },
        { value: "cherry", label: "Select cherry" },
        { value: "oak", label: "Select red oak" },
      ] },
      { id: "heightIn", label: "Overall height (in)", kind: "number", required: true },
      { id: "leftWidthIn", label: "Left tower width (in)", kind: "number", required: true },
      { id: "centerWidthIn", label: "Center width (in)", kind: "number", required: true },
      { id: "rightWidthIn", label: "Right tower width (in)", kind: "number", required: true },
      { id: "depthIn", label: "Depth (in)", kind: "number", required: true },
      { id: "seatHeightIn", label: "Seat height (in)", kind: "number", required: true },
      { id: "upperClearIn", label: "Upper storage, clear (in)", kind: "number", required: true },
      { id: "upperBays", label: "Upper bays", kind: "integer", required: true },
      { id: "cubbies", label: "Cubbies under the seat", kind: "integer", required: true },
      { id: "leftShelves", label: "Left tower shelves", kind: "integer", required: true },
      { id: "rightShelves", label: "Right tower shelves", kind: "integer", required: true },
      { id: "frontAdded", label: "Add a front board", kind: "boolean", required: true },
      { id: "sideSpot", label: "Side spots", kind: "choice", required: false, choices: [
        { value: "", label: "None" },
        { value: "CENTER", label: "Centered" },
        { value: "1.5", label: "1½ in from the edge" },
        { value: "2", label: "2 in from the edge" },
      ] },
    ],
    defaults: {
      species: "pine",
      heightIn: 94,
      leftWidthIn: 24,
      centerWidthIn: 55,
      rightWidthIn: 24,
      depthIn: 14,
      seatHeightIn: 22,
      upperClearIn: 14,
      upperBays: 2,
      cubbies: 2,
      leftShelves: 4,
      rightShelves: 4,
      frontAdded: false,
      sideSpot: "",
    },
    rule: { op: "window-seat-layout" },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "outdoor",
    version: "1",
    title: "Outdoor",
    summary: "Two published picnic-table plans. You choose the plan, the length and the wood.",
    narrative:
      "Nothing is sent until you choose a plan. Slats follow the length you set. Legs, angles and the short parts stay as the plan published them. Hardware is a requirement, not a Store SKU, and only if you pick a finish. Bring-your-own sends no hardware line.",
    engine: "supported",
    requestType: "CUT_PACKAGE_V1",
    configurationId: "OUTDOOR-PICNIC",
    requirements: {
      endRelation: "as-published-on-the-plan",
      lengthDatum: "long-point-to-short-point",
      endIdentity: "plan-end",
    },
    inputs: [
      { id: "planId", label: "Plan", kind: "choice", required: true, choices: [
        { value: "a-frame", label: "Classic A-frame" },
        { value: "table-benches", label: "Table and two benches" },
      ] },
      { id: "lengthIn", label: "Slat length (in)", kind: "number", required: true },
      { id: "wood", label: "Wood", kind: "choice", required: true, choices: woodChoices },
      { id: "hardwareTier", label: "Hardware", kind: "choice", required: true, choices: finishes },
    ],
    defaults: { planId: "", lengthIn: 72, wood: "", hardwareTier: "BYO" },
    rule: { op: "plan-groups", planId: { input: "planId" }, lengthIn: { input: "lengthIn" }, wood: { input: "wood" }, hardwareTier: { input: "hardwareTier" }, plans, woods },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "playhouse",
    version: "1",
    title: "Playhouse window",
    summary: "One sheet, one arched opening, a center split, and two crosscuts.",
    narrative:
      "The opening is a width, a straight height and a rise. The radius is width² / (8 × rise) + rise / 2. Tabs stay on the opening. Both offcuts come back. A crosscut that hits the opening is the Store's refusal. This page does not move it.",
    engine: "supported",
    requestType: "SHEET_PACKAGE_V1",
    configurationId: "PLAYHOUSE-ARCHED-WINDOW",
    requirements: {
      endRelation: "sheet-edges",
      lengthDatum: "sheet-left-end",
      endIdentity: "factory-edge",
    },
    inputs: [
      { id: "widthIn", label: "Opening width (in)", kind: "number", required: true },
      { id: "straightHeightIn", label: "Straight height (in)", kind: "number", required: true },
      { id: "riseIn", label: "Arch rise (in)", kind: "number", required: true },
      { id: "cutLeftIn", label: "Crosscut from the left (in)", kind: "number", required: true },
      { id: "cutRightIn", label: "Crosscut from the right (in)", kind: "number", required: true },
      { id: "thicknessIn", label: "Sheet thickness (in)", kind: "number", required: true },
      { id: "sheetLengthIn", label: "Sheet length (in)", kind: "number", required: true },
      { id: "sheetWidthIn", label: "Sheet width (in)", kind: "number", required: true },
    ],
    defaults: {
      widthIn: 36,
      straightHeightIn: 24,
      riseIn: 12,
      cutLeftIn: 18,
      cutRightIn: 18,
      thicknessIn: 0.5,
      sheetLengthIn: 96,
      sheetWidthIn: 48,
    },
    rule: {
      op: "sheet-opening",
      widthIn: { input: "widthIn" },
      straightHeightIn: { input: "straightHeightIn" },
      riseIn: { input: "riseIn" },
      cutLeftIn: { input: "cutLeftIn" },
      cutRightIn: { input: "cutRightIn" },
      thicknessIn: { input: "thicknessIn" },
      sheetLengthIn: { input: "sheetLengthIn" },
      sheetWidthIn: { input: "sheetWidthIn" },
    },
  },
  {
    schema: RECIPE_SCHEMA,
    recipeId: "closet-cleats",
    version: "1",
    title: "Closet cleats",
    summary: "A sixth job. Data only. Square-cut cedar cleats. No new compiler rule.",
    narrative:
      "Three groups of square cuts on cedar 2×4: two long cleats and one shorter center cleat. No rip, no miter, no hardware, no spots. It uses the same part-groups rule as any other cut list. Nothing in the compiler is named for a closet.",
    engine: "supported",
    requestType: "CUT_PACKAGE_V1",
    configurationId: "CLOSET-CLEATS",
    requirements: requirementsSquare,
    inputs: [
      { id: "species", label: "Species", kind: "text", required: true },
      { id: "grade", label: "Grade", kind: "text", required: true },
      { id: "longIn", label: "Long cleat (in)", kind: "number", required: true },
      { id: "shortIn", label: "Center cleat (in)", kind: "number", required: true },
    ],
    defaults: { species: "cedar", grade: "S4S", longIn: 32, shortIn: 18 },
    rule: {
      op: "part-groups",
      configurationVersion: "1",
      groups: [
        {
          id: { literal: "CLEATS" },
          species: { input: "species" },
          grade: { input: "grade" },
          nominalT: { literal: 2 },
          nominalW: { literal: 4 },
          angleDeg: { literal: 0 },
          parts: [
            { id: { literal: "CLEAT-LONG" }, count: { literal: 2 }, lengthIn: { input: "longIn" } },
            { id: { literal: "CLEAT-SHORT" }, count: { literal: 1 }, lengthIn: { input: "shortIn" } },
          ],
        },
      ],
    },
  },
];

export function recipeById(id: string): Recipe | undefined {
  return LIBRARY.find((recipe) => recipe.recipeId === id);
}
