/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ApiStoreZeroJobRouteImport } from './routes/api/store-zero/job'
import { Route as ApiStoreZeroOfferingRouteImport } from './routes/api/store-zero/offering'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreZeroJobRoute = ApiStoreZeroJobRouteImport.update({
  id: '/api/store-zero/job',
  path: '/api/store-zero/job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreZeroOfferingRoute = ApiStoreZeroOfferingRouteImport.update({
  id: '/api/store-zero/offering',
  path: '/api/store-zero/offering',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/healthz': typeof HealthzRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/store-zero/job': typeof ApiStoreZeroJobRoute
  '/api/store-zero/offering': typeof ApiStoreZeroOfferingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/healthz': typeof HealthzRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/store-zero/job': typeof ApiStoreZeroJobRoute
  '/api/store-zero/offering': typeof ApiStoreZeroOfferingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/healthz': typeof HealthzRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/store-zero/job': typeof ApiStoreZeroJobRoute
  '/api/store-zero/offering': typeof ApiStoreZeroOfferingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bench'
    | '/healthz'
    | '/projects/$projectId'
    | '/api/store-zero/job'
    | '/api/store-zero/offering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bench'
    | '/healthz'
    | '/projects/$projectId'
    | '/api/store-zero/job'
    | '/api/store-zero/offering'
  id:
    | '__root__'
    | '/'
    | '/bench'
    | '/healthz'
    | '/projects/$projectId'
    | '/api/store-zero/job'
    | '/api/store-zero/offering'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRoute: typeof BenchRoute
  HealthzRoute: typeof HealthzRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiStoreZeroJobRoute: typeof ApiStoreZeroJobRoute
  ApiStoreZeroOfferingRoute: typeof ApiStoreZeroOfferingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-zero/job': {
      id: '/api/store-zero/job'
      path: '/api/store-zero/job'
      fullPath: '/api/store-zero/job'
      preLoaderRoute: typeof ApiStoreZeroJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-zero/offering': {
      id: '/api/store-zero/offering'
      path: '/api/store-zero/offering'
      fullPath: '/api/store-zero/offering'
      preLoaderRoute: typeof ApiStoreZeroOfferingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRoute: BenchRoute,
  HealthzRoute: HealthzRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiStoreZeroJobRoute: ApiStoreZeroJobRoute,
  ApiStoreZeroOfferingRoute: ApiStoreZeroOfferingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
